In [45]:
import pandas as pd

In [46]:
AggregateData_Train=pd.read_csv("AggregateData_Train.csv")

In [47]:
AggregateData_Train.head()

,UID,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V45,V46,V47,V48,V49,V50,V51,V52,V53,bad_flag
0,Tr-1,61P4S1M3GET,10397.75,?,?,?,?,?,?,197186.68,...,?,5.04055,?,?,?,6,9,3,10,0
1,Tr-2,6NYVS1J3U7M,?,606.74,?,?,?,?,?,?,...,?,?,?,?,?,1,?,?,?,0
2,Tr-3,BLFB1KMS48,87452.89,963.52,?,?,13838,?,?,1081.25,...,?,?,?,?,?,10,10,20,1,0
3,Tr-4,MYGB1LCW8P,?,393.26,100000,?,?,?,?,?,...,?,?,?,?,?,4,1,?,2,0
4,Tr-5,6UG5S1PQGE5,1100,497.2,?,?,?,?,0.9,18640,...,?,0.00470,?,?,0.00007,2,3,1,2,0

In [48]:
AggregateData_Train.shape

(26775, 54)

In [49]:
AggregateData_Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26775 entries, 0 to 26774
Data columns (total 54 columns):
UID         26775 non-null object
V2          26775 non-null object
V3          26775 non-null object
V4          26775 non-null object
V5          26775 non-null object
V6          26775 non-null object
V7          26775 non-null object
V8          26775 non-null object
V9          26775 non-null object
V10         26775 non-null object
V11         26775 non-null object
V12         26775 non-null object
V13         26775 non-null object
V14         26775 non-null object
V15         26775 non-null object
V16         26775 non-null object
V17         26775 non-null object
V18         26775 non-null object
V19         26775 non-null object
V20         26775 non-null object
V21         26775 non-null object
V22         26775 non-null object
V23         26775 non-null object
V24         26775 non-null object
V25         26775 non-null object
V26         26775 non-null object
V27         26775 non-null object
V28         26775 non-null object
V29         26775 non-null object
V30         26775 non-null object
V31         26775 non-null object
V32         26775 non-null object
V33         26775 non-null object
V34         26775 non-null object
V35         26775 non-null object
V36         26775 non-null object
V37         26775 non-null object
V38         26775 non-null object
V39         26775 non-null object
V40         26775 non-null object
V41         26775 non-null object
V42         26775 non-null object
V43         26775 non-null object
V44         26775 non-null object
V45         26775 non-null object
V46         26775 non-null object
V47         26775 non-null object
V48         26775 non-null object
V49         26775 non-null object
V50         26775 non-null object
V51         26775 non-null object
V52         26775 non-null object
V53         26775 non-null object
bad_flag    26775 non-null int64
dtypes: int64(1), object(53)
memory usage: 11.0+ MB

In [50]:
sample_submission=pd.read_csv("sample_submission.csv")
sample_submission.shape

(10, 2)

In [51]:
sample_submission

     UID  bad_flag
0   Te-1  0.054400
1   Te-2  0.084719
2   Te-3  0.049044
3   Te-4  0.095034
4   Te-5  0.065099
5   Te-6  0.034086
6   Te-7  0.025697
7   Te-8  0.076009
8   Te-9  0.117930
9  Te-10  0.051464

In [52]:
TransactionData_Train=pd.read_csv("TransactionData_Train.csv")
TransactionData_Train.shape

(3343745, 9)

In [53]:
AggregateData_Test=pd.read_csv("AggregateData_Test.csv")
AggregateData_Test.shape

(48434, 53)

In [54]:
TransactionData_Test=pd.read_csv("TransactionData_Test.csv")
TransactionData_Test.shape

(2648039, 9)

In [55]:
TransactionData_Train.head()

,C2,C3,C4,C5,C6,C8,C9,C10,C12
0,6UGH4BMM1Y6P,6YPV4HMP1V5EWID,06JUL38:17:31:02,D,IAD,2038-12-30,30JUL38:00:00:00,OTHER,22000.0
1,9Y46ZBCWRP9,61CE41JD5YMP329,05MAY38:16:46:36,D,STD,2039-06-31,28MAY38:00:00:00,FT,8183.0
2,6Z4F3BPVME6,6UQA3CP9F95BOBD,08FEB37:15:55:28,C,OCD,2038-04-31,30FEB37:00:00:00,CHQ,48900.0
3,6UYF21TDMPPT,BZF6Z3AJQ55MAM,24NOV38:09:48:37,D,EAW,2039-05-29,31NOV38:00:00:00,ATM,1500.0
4,5N5ASLGMMPM,6IPA43AM4Y613SX,26OCT38:18:54:06,D,ATW,2038-03-31,31OCT38:00:00:00,ATM,10000.0

In [56]:
TransactionData_Test.head()

,C2,C3,C4,C5,C6,C8,C9,C10,C12
0,IYH6EOT91IN,6I5V3CKDUVTER3U,16JAN37:23:42:31,D,RDD,2038-02-30,31JAN37:00:00:00,SWEEP,1000.00
1,6NF44HKS8VNP,68BV39T3U86732X,01MAR37:10:24:25,D,NWD,2038-12-30,31MAR37:00:00:00,ATM,10000.00
2,6LFE2QYJ56TM,6UHW3BHJGEWE93X,23APR38:09:33:09,C,MCR,2038-07-30,31APR38:00:00:00,OTHER,23591.24
3,61QE4KT94V5N,6XBA4KPWF94NEBQ,30SEP38:17:30:56,D,ETD,2039-05-29,30SEP38:00:00:00,OTHER,24000.00
4,6XGA3KPVR7WH,5NFF4KADUV41J,23DEC37:19:37:08,C,OCD,2038-01-31,30DEC37:00:00:00,CHQ,4076.00

In [57]:
print(set(TransactionData_Test['C5']))
print(set(TransactionData_Test['C10']))

{'C', 'D'}
{'ATM', 'NEFT', 'RTGS', 'CHG', 'FCC', 'TAX', 'FT', 'OTHER', 'CHQ', 'Interest', 'ECS', 'CMS', 'IMPS', 'Deal pro', 'ENET', 'SWEEP'}

In [58]:
print(set(TransactionData_Train['C5']))
print(set(TransactionData_Test['C10']))

{'C', 'D'}
{'ATM', 'NEFT', 'RTGS', 'CHG', 'FCC', 'TAX', 'FT', 'OTHER', 'CHQ', 'Interest', 'ECS', 'CMS', 'IMPS', 'Deal pro', 'ENET', 'SWEEP'}

In [59]:
AggregateData_Test.head()

,UID,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V44,V45,V46,V47,V48,V49,V50,V51,V52,V53
0,Te-1,61P4S1M3GET,10397.75,?,?,?,?,?,?,197186.68,...,?,?,5.04055,?,?,?,6,9,3,10
1,Te-2,6NYVS1J3U7M,?,606.74,?,?,?,?,?,?,...,?,?,?,?,?,?,1,?,?,?
2,Te-3,BLFB1KMS48,87452.89,963.52,?,?,13838,?,?,1081.25,...,1.28678,?,?,?,?,?,10,10,20,1
3,Te-4,MYGB1LCW8P,?,393.26,100000,?,?,?,?,?,...,?,?,?,?,?,?,4,1,?,2
4,Te-5,6UG5S1PQGE5,1100,497.2,?,?,?,?,0.9,18640,...,?,?,0.00470,?,?,0.00007,2,3,1,2

In [60]:
AggregateData_Test.describe()

,UID,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V44,V45,V46,V47,V48,V49,V50,V51,V52,V53
count,48434,48434,48434,48434,48434,48434,48434,48434,48434,48434,...,48434,48434,48434,48434,48434,48434,48434,48434,48434,48434
unique,48434,25719,9565,12664,648,980,1710,34,369,1654,...,1914,686,4645,300,35,313,126,176,162,177
top,Te-39137,61CW43PD8Y9P,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,?
freq,1,8,28150,9912,47026,45905,44833,48371,47668,45067,...,44833,47133,38942,47863,48371,47668,24491,21297,29193,21590

In [61]:
AggregateData_Train.isnull().sum()

UID         0
V2          0
V3          0
V4          0
V5          0
V6          0
V7          0
V8          0
V9          0
V10         0
V11         0
V12         0
V13         0
V14         0
V15         0
V16         0
V17         0
V18         0
V19         0
V20         0
V21         0
V22         0
V23         0
V24         0
V25         0
V26         0
V27         0
V28         0
V29         0
V30         0
V31         0
V32         0
V33         0
V34         0
V35         0
V36         0
V37         0
V38         0
V39         0
V40         0
V41         0
V42         0
V43         0
V44         0
V45         0
V46         0
V47         0
V48         0
V49         0
V50         0
V51         0
V52         0
V53         0
bad_flag    0
dtype: int64

In [62]:
test_id = AggregateData_Test['UID']

In [63]:
y_train=AggregateData_Train['bad_flag']
y_train.shape

(26775,)

In [64]:
x_train=AggregateData_Train.drop(['UID','V2'],axis=1)
x_train.shape

(26775, 52)

In [65]:
x_train=x_train.drop(['bad_flag'],axis=1)

In [66]:
x_test=AggregateData_Test.drop(['UID','V2'],axis=1)

In [67]:
from sklearn.preprocessing import StandardScaler
from sklearn import ensemble

In [68]:
sc= StandardScaler()

In [69]:
clf = ensemble.GradientBoostingRegressor(n_estimators = 2000,max_features='log2', max_depth = 40, min_samples_split = 2,
          learning_rate = 0.8, loss = 'ls')

In [70]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [71]:
x_train=x_train.apply(le.fit_transform)

In [72]:
x_train.head()

,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,...,V44,V45,V46,V47,V48,V49,V50,V51,V52,V53
0,167,12651,646,974,1707,33,367,539,990,669,...,1911,684,4004,298,34,311,87,164,80,1
1,9553,10066,646,974,1707,33,367,1651,990,669,...,1911,684,4633,298,34,311,0,175,161,176
2,9012,12445,646,974,269,33,367,78,746,422,...,1583,684,4633,298,34,311,1,1,57,0
3,9553,7897,3,974,1707,33,367,1651,990,669,...,1911,684,4633,298,34,311,64,0,161,64
4,413,9101,646,974,1707,33,0,499,990,669,...,1911,684,308,298,34,7,35,88,0,64

In [73]:
x_test=x_test.apply(le.fit_transform)

In [74]:
x_test.head()

,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,...,V44,V45,V46,V47,V48,V49,V50,V51,V52,V53
0,168,12663,647,979,1709,33,368,539,990,670,...,1913,685,4012,299,34,312,87,164,80,1
1,9564,10073,647,979,1709,33,368,1653,990,670,...,1913,685,4644,299,34,312,0,175,161,176
2,9023,12457,647,979,270,33,368,78,746,422,...,1584,685,4644,299,34,312,1,1,57,0
3,9564,7905,3,979,1709,33,368,1653,990,670,...,1913,685,4644,299,34,312,64,0,161,64
4,414,9107,647,979,1709,33,0,499,990,670,...,1913,685,308,299,34,7,35,88,0,64

In [75]:
x_train = sc.fit_transform(x_train)
x_test= sc.transform(x_test)

C:\Users\Deepak\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int32 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Deepak\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Deepak\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int32 were all converted to float64 by StandardScaler.

In [76]:
clf.fit(x_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.8, loss='ls', max_depth=40,
             max_features='log2', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=2000,
             n_iter_no_change=None, presort='auto', random_state=None,
             subsample=1.0, tol=0.0001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [77]:
pred=clf.predict(x_test)

In [78]:
print(type(pred))

<class 'numpy.ndarray'>

In [79]:
pred

array([-8.44766524e-06,  1.25499398e-05, -1.26401686e-06, ...,
        2.55766762e-06, -2.27090854e-08,  1.07664244e-05])

In [80]:
import numpy as np

In [81]:
pred=pred.tolist()

In [82]:
pred

[-8.447665240605675e-06,
 1.2549939760062694e-05,
 -1.2640168636997523e-06,
 -5.0651825195207356e-06,
 9.634542058803416e-07,
 2.624997489354662e-06,
 1.9004965319555777e-09,
 -3.909851740327477e-06,
 1.0918098692681331e-05,
 -0.0001283520539752239,
 1.4500545456560441e-05,
 1.5810003146049634e-07,
 0.11547344108315394,
 2.5858354491435994e-05,
 -1.202472653826223e-06,
 -2.435992788786949e-05,
 8.63830814969134e-06,
 -6.573630399999976e-06,
 -6.356535578261461e-06,
 0.00010257240863302402,
 -1.035187438653128e-06,
 3.2356658577662873e-06,
 2.4864072540899676e-05,
 -5.6997186754057274e-08,
 7.337173018717254e-06,
 -1.8413972259201036e-06,
 -1.9381282960573368e-05,
 3.8610742275268457e-05,
 -4.493983040596641e-06,
 1.647323379053931e-07,
 -6.0228105256510635e-06,
 1.1828865038356248e-05,
 -2.0209949363048375e-06,
 7.260817649656817e-07,
 0.11547344108315394,
 4.028066311088081e-09,
 -1.590124519511411e-06,
 -2.6061862910340737e-06,
 -2.6520741249348043e-06,
 -1.4472372877717311e-05,
 -1.9187106807462373e-08,
 0.002868669840002861,
 3.609762973735789e-06,
 -7.701120819873218e-06,
 2.4382806598726063e-07,
 2.0541904520043028e-07,
 8.265633248931074e-05,
 0.00020298557486186748,
 0.020610848419256176,
 -4.0785520764712064e-05,
 0.00374302067156187,
 -1.3600808016254e-05,
 3.653469983222069e-05,
 0.00035988583612069417,
 2.0243848272864898e-08,
 1.936033148463838e-09,
 1.3876905145733321e-08,
 8.05422891505003e-09,
 -2.368852607645372e-08,
 -3.440218951154275e-05,
 2.9591795840580467e-07,
 1.0512861725893382e-05,
 7.722924508311499e-05,
 7.2785585452296645e-06,
 -3.311127940718189e-09,
 -2.2652116572777496e-05,
 -0.00015432479481377971,
 7.089083127794132e-06,
 0.00014301980963876064,
 -9.495741207366403e-06,
 0.9998041678054574,
 1.2433085397880286e-05,
 -4.2829417199841535e-06,
 3.284379074384978e-05,
 -2.289500429256485e-06,
 -1.3236833585318443e-06,
 1.344762928489194e-06,
 3.2467139026021926e-06,
 -4.267114922341675e-05,
 1.8679992128707764e-06,
 0.00011867795162354597,
 0.9998515577560722,
 1.0000052696467583,
 1.2387895616448736e-08,
 -6.071217547426153e-09,
 -9.157133421518839e-06,
 -3.7675371738883923e-07,
 2.4575249993379496e-06,
 -2.814231758531239e-05,
 2.0528544764845048e-05,
 2.0797288101307108e-05,
 -1.5396865249886416e-07,
 2.4661417331130896e-05,
 -1.0184563536109662e-06,
 6.453348420945599e-05,
 4.179832631765136e-06,
 -6.0570466825502e-07,
 3.257174899699125e-07,
 2.4425678226550016e-09,
 -1.9416298806932312e-08,
 5.314967319515587e-07,
 1.668913035965437e-10,
 -1.2344218271622252e-08,
 -3.3775679892133302e-06,
 -7.308368490673392e-08,
 6.617068959719403e-08,
 -1.565616200983069e-05,
 4.488378044137432e-06,
 -2.3912913825247268e-05,
 1.0550521423623941e-05,
 -5.594925686669147e-08,
 0.00016239006769814927,
 0.0013262695609150626,
 9.614954827133771e-06,
 5.022918784935826e-07,
 3.5487269892469946e-05,
 -8.610856871210627e-05,
 -7.096494303852716e-05,
 6.306940276465187e-10,
 -2.3242851823084727e-05,
 0.00010508578704638003,
 3.947096709502124e-05,
 3.223574656837344e-05,
 1.1127224246557622e-07,
 6.9746787975388124e-06,
 4.94197671476002e-08,
 0.9999649756840501,
 -4.7363123286477675e-08,
 1.8602581777623881e-06,
 8.634561111208052e-06,
 -4.920396481840688e-06,
 9.650227638195751e-09,
 0.00014281109306419685,
 8.604886799051285e-06,
 -2.6774415552800955e-07,
 3.143894208615537e-05,
 -6.571072916951488e-09,
 0.005893324544597048,
 5.080778060963612e-08,
 -4.921503823851893e-06,
 2.1239707653680118e-05,
 -3.787443806038455e-05,
 -1.1818279304193568e-05,
 3.4705088155087567e-05,
 8.154084739791815e-05,
 -4.234108254911377e-07,
 2.587030671389052e-09,
 5.884404989868113e-08,
 1.1723352376957448e-06,
 3.289132901574612e-07,
 -3.1875104799520676e-06,
 5.283108809089974e-05,
 3.3127919062019724e-06,
 0.9999917301324811,
 3.3492036466168305e-06,
 -1.0937465779504678e-06,
 -8.685196630798179e-08,
 1.102170499812391e-06,
 -4.075889950730377e-08,
 4.987843218774684e-06,
 -2.834127028990971e-05,
 -2.8263096813796743e-05,
 0.9999105498400045,
 -1.2190857539753168e-05,
 -3.993062353703363e-07,
 -8.661834484888258e-06,
 -1.5660671004987657e-05,
 -5.225187324637439e-09,
 0.9999876425124877,
 7.269437714371218e-05,
 -1.3795337326925391e-05,
 -1.55897210458202e-05,
 -4.2321129840800136e-05,
 -3.8947956255520614e-06,
 -6.295801397096153e-08,
 3.7392705149078233e-08,
 -1.5634069445211625e-05,
 -2.1546758171705532e-05,
 -9.649407846551783e-07,
 -1.8166027180352766e-06,
 5.908023515071172e-06,
 0.000135559379034237,
 -3.5751831561541286e-06,
 -3.552875953866549e-09,
 3.3595268306327804e-05,
 -1.2863330147504148e-06,
 6.831202390205522e-06,
 1.3908597845879696e-07,
 0.9999986551739454,
 7.4378048662295525e-06,
 -3.1214534180900696e-06,
 3.738786021247237e-05,
 -3.56044637569859e-07,
 -3.298412586052169e-09,
 1.0000000945219,
 8.87610386185617e-06,
 -0.0004469832443381445,
 1.6841443796202396e-07,
 4.353888590612403e-05,
 3.3332391323099107e-05,
 1.7202715926548247e-07,
 -2.0058958223892437e-07,
 0.7998859614021223,
 1.2156760140810926e-05,
 2.192661463905795e-05,
 1.3615476019196295e-05,
 1.78892026672824e-06,
 -0.00010336550240640874,
 3.3080609371519846e-05,
 -6.422084729114177e-06,
 3.52202684090338e-05,
 -3.9006024214660895e-05,
 3.285642250340599e-07,
 6.186093327924754e-05,
 -1.2579643797130432e-07,
 0.00014620063455195124,
 -7.1114261369828294e-06,
 -3.832859349959294e-06,
 -8.631340932839549e-05,
 -7.806680166221293e-05,
 8.478329749017464e-05,
 -2.8525854319535104e-05,
 3.4695481337267746e-08,
 2.4720539730578353e-08,
 1.541967600308811e-08,
 -3.261296263422232e-05,
 2.7811532515910513e-05,
 -7.574183995521031e-06,
 -2.7286290397769958e-08,
 -1.8231379611823585e-06,
 -4.4851150009102706e-06,
 -1.7387478937783758e-05,
 -9.07445234362157e-06,
 0.9999998221189998,
 2.4228531551199757e-07,
 6.42213705796201e-06,
 1.168153836073637e-05,
 6.985994740660678e-06,
 3.429518941195849e-07,
 -2.264637913193272e-08,
 1.072137302249094e-06,
 -6.479104118392167e-08,
 -8.018716100079667e-09,
 4.063689446909387e-06,
 2.41224146736822e-07,
 6.284923612866074e-07,
 -3.825079356441975e-06,
 -5.420440551663275e-08,
 1.3131509861966675e-07,
 8.064864323708113e-09,
 4.526405883391035e-05,
 4.49942332726962e-07,
 1.552346023552072e-06,
 2.7411111991226173e-06,
 0.057243264366900304,
 4.019393430424718e-09,
 -1.7188973308073037e-06,
 -2.075954857512633e-05,
 1.1894986816433877e-05,
 1.3531088128208737e-05,
 -4.2199469908757156e-05,
 2.3784903777419983e-05,
 -4.096908137811351e-06,
 0.159782394412483,
 1.0000000416669745,
 2.4454113142791026e-07,
 -1.59257275435363e-05,
 7.681024160811212e-05,
 0.9999989842921662,
 -4.183826691385586e-06,
 3.4013617315757785e-05,
 3.614034879988038e-05,
 -4.1298110063831646e-07,
 7.000938476242109e-06,
 -6.0799997244308624e-06,
 -7.20775567830571e-07,
 -3.898386738835124e-10,
 5.299404563084734e-05,
 8.105449294989674e-05,
 2.852750643593035e-06,
 -2.081462583858543e-08,
 -7.015215481102573e-06,
 4.538744140499466e-06,
 6.514726847043237e-09,
 -2.4156448250376264e-08,
 2.082933002094029e-06,
 -5.036867521238897e-05,
 4.3570682452547155e-07,
 8.817233797301206e-06,
 -3.653921901463017e-06,
 1.0436234873266701e-05,
 0.8400066915436609,
 3.7723994183509244e-06,
 0.00010828923673789184,
 0.7304261866756806,
 8.92647379777272e-05,
 -3.606268804019946e-09,
 8.436154346638394e-06,
 -1.3578975920598431e-05,
 -1.3142699266119657e-06,
 -7.980201017480007e-06,
 0.9999819380315594,
 6.093950567644005e-06,
 -2.001921208869213e-05,
 -8.429757144697223e-08,
 -1.1512629472834992e-06,
 -5.062500364160463e-06,
 1.347693678948921e-06,
 -1.9826252785131805e-05,
 -4.155573171609287e-05,
 2.1107026028140297e-08,
 -9.767464851079304e-06,
 1.2807633197646215e-05,
 0.9999457233811468,
 2.793366786241765e-07,
 2.774671386224841e-05,
 -3.014843777741583e-05,
 -2.5936860025552476e-05,
 1.4340892770693623e-05,
 -7.160923222520907e-05,
 8.373497076818145e-06,
 6.85992916419048e-08,
 0.8000145951600335,
 6.456310070189504e-06,
 -6.997170912836197e-05,
 0.000126414947489041,
 1.6733778244510174e-05,
 -9.449262655319036e-07,
 -1.1289028960185584e-07,
 0.9997428452162139,
 9.23749086357049e-07,
 -8.775656627426218e-07,
 8.550130409710775e-06,
 3.941775310978998e-06,
 -6.755927423885953e-05,
 1.0514043015492575e-05,
 2.9391936240677376e-05,
 -7.909878176523159e-06,
 -1.4408538742863907e-06,
 -2.197178695420581e-06,
 7.996175730595067e-06,
 5.34351570259076e-07,
 2.1300929376652506e-06,
 2.7864675961767164e-05,
 -9.629113581749285e-06,
 -2.393962968591843e-06,
 -6.135313065807831e-06,
 -8.891195213870768e-09,
 2.2037740937621182e-06,
 0.09079619910051029,
 -0.00019580510731935448,
 0.014970257204133983,
 1.7512323265934655e-05,
 0.9943338789011498,
 0.20586537048694414,
 1.1941201157003202e-06,
 -4.737614640352694e-05,
 0.9999817052347408,
 -6.730836987707365e-09,
 5.165111986498553e-07,
 0.3657714468344885,
 4.782365748610704e-06,
 4.2138389782819735e-07,
 5.2542937726486765e-05,
 -1.0341207387374019e-07,
 -1.0761680216055568e-05,
 -1.2520261423688438e-05,
 0.00015681574088986978,
 9.681465731106601e-06,
 -1.5832488935341623e-05,
 -0.00012002833648792956,
 -7.056580418670285e-06,
 1.2182574550231344e-09,
 -0.00015178750122720114,
 -1.7551158336871947e-06,
 -4.667932664074793e-06,
 5.894048184875334e-06,
 -1.3837347253744583e-06,
 -1.616890430771912e-06,
 -0.034577998235975856,
 -1.4382566233335353e-08,
 3.269847234958559e-07,
 1.0331123866523216e-07,
 -3.216583534615445e-06,
 1.2964877478242242e-06,
 4.809672955452798e-05,
 3.0186963580462814e-07,
 1.294860682328758e-06,
 -1.458160936051652e-07,
 4.465571875308611e-07,
 1.0000470409425661,
 -9.35194242432323e-06,
 3.8629237380974987e-07,
 4.736600918025426e-06,
 8.447184579757387e-09,
 5.892166077380198e-06,
 2.0946285743822026e-07,
 3.096887558495787e-06,
 5.072630939970652e-06,
 1.918835076239553e-09,
 -4.049520820181063e-05,
 -4.1510294394788706e-05,
 -1.0836988954898209e-05,
 5.739016547002147e-09,
 -9.969647359414372e-05,
 -2.5127841929462287e-06,
 0.00010178969997229724,
 3.6923480749500113e-06,
 -2.0936592538132144e-05,
 -9.677644042508987e-09,
 -6.792567234305774e-08,
 0.0001693928275276503,
 0.9999999891540496,
 -2.26473532637726e-06,
 6.593299879635522e-07,
 5.665461298885094e-07,
 8.254240307265259e-07,
 -1.5082378223659358e-06,
 4.165116334289341e-05,
 1.3377803076778152e-05,
 -1.966662805489095e-06,
 2.825192513494051e-07,
 5.28221059690849e-05,
 -1.6590652600015678e-06,
 3.196686862339653e-05,
 1.324831805425697e-08,
 4.57839720196716e-06,
 2.1902716803711356e-07,
 1.8504326929935165e-08,
 8.96248856991506e-05,
 2.322455450441232e-06,
 2.036494136054871e-05,
 2.3888866448807316e-07,
 -4.523941914231373e-06,
 3.5438963165056556e-05,
 -7.6181136407062e-05,
 1.902571308775331e-05,
 1.3195450900563855e-05,
 7.700736673324422e-06,
 1.581977516931701e-05,
 3.7742094603280866e-06,
 9.737829235054031e-06,
 -1.0128427827748021e-05,
 3.102887025606381e-05,
 9.866819855181045e-05,
 1.506855562776774e-06,
 -7.450250706636633e-07,
 -6.737044902363008e-07,
 3.376928604211043e-07,
 0.00031585249108632914,
 3.822848533052858e-08,
 1.1700429151724099e-07,
 0.11547344108315394,
 0.9999999941981736,
 -2.9126445513794522e-05,
 3.4852536769038096e-06,
 1.2568613888383322e-07,
 -6.78455433312261e-06,
 -9.739968285483245e-08,
 -2.1325793538339754e-05,
 -1.3029914523607508e-05,
 -3.202999614463958e-07,
 5.727801720423753e-08,
 1.5540635470095433e-05,
 0.0006800140968920696,
 7.383289971852991e-06,
 -1.2341494454306916e-06,
 2.2599803408100035e-05,
 0.0002176114938749504,
 -1.3227886753236557e-05,
 -2.5104048832545055e-05,
 7.558423907796496e-05,
 0.9999990740218093,
 2.5031125964967507e-06,
 6.6270899481493175e-06,
 2.994539665005659e-05,
 1.5687899296345437e-05,
 -5.508336996047794e-07,
 1.2062563678705294e-06,
 5.312876802904953e-06,
 7.513402978862608e-06,
 -5.6905987999272666e-08,
 0.12867647058823525,
 0.11547344108315394,
 3.9020681535209316e-07,
 0.20006691940691,
 3.3261280329834678e-06,
 -1.04300723335281e-05,
 2.3058540234473135e-05,
 -1.4514433331557064e-05,
 -8.567503948845923e-06,
 2.0914179075254133e-07,
 -4.523119534407224e-05,
 2.9658166521248686e-06,
 -7.622049415490548e-09,
 1.3579026787107489e-06,
 2.285317440082343e-07,
 0.9999778313634435,
 2.4778199120397348e-05,
 4.92932555886036e-06,
 -4.6918750474036675e-05,
 -1.6140267034345649e-06,
 -1.249100923241654e-06,
 1.7410648402079256e-05,
 -7.787147450323754e-06,
 -4.4319973654966784e-07,
 -1.5745278122736666e-05,
 -8.403408874264948e-09,
 -2.8530989010362986e-05,
 4.374456068435459e-06,
 1.000000156608592,
 -2.3555258071633264e-05,
 -3.8945743944473544e-05,
 -3.981316404943016e-05,
 7.300174864143449e-06,
 1.9181184408492662e-05,
 7.656573063990452e-07,
 -5.039132736863132e-06,
 0.00024369121655830624,
 -1.3987665810187623e-06,
 2.2117278344816263e-05,
 -3.3031379676928745e-07,
 -1.1119588931969557e-05,
 3.0513728393378925e-05,
 8.015130850989281e-08,
 2.133925867905071e-05,
 1.0233410993591453e-05,
 -4.8104108587726226e-05,
 5.2023704808824146e-08,
 2.6464588843717157e-05,
 -7.2243377385987285e-06,
 0.0001222814130701887,
 5.0021705522495685e-05,
 3.94782030629145e-06,
 5.775028989763191e-07,
 -1.2040802250324316e-06,
 1.62402274267966e-05,
 0.9999687883400942,
 -1.1443787560155998e-05,
 -3.84404986387491e-06,
 7.113206345429203e-06,
 -8.790670345576222e-07,
 2.2376873635681776e-06,
 1.608493722878287e-08,
 0.9999819036922271,
 7.0268024006642445e-06,
 2.6364770410088736e-06,
 -5.44657193089407e-05,
 9.857167871116124e-10,
 -5.4034660726177036e-05,
 3.2901803075221154e-07,
 2.1527851677057555e-06,
 -1.1178866157770468e-06,
 2.804711390516906e-08,
 1.6261033835594785e-06,
 -3.094191327524397e-06,
 -2.8733880091491505e-08,
 -1.1761387916608162e-05,
 -1.643573764288271e-05,
 0.9999504841982778,
 1.0000000172800083,
 9.124950539876371e-10,
 -1.373868053979941e-05,
 -1.3708139094101096e-08,
 1.780675760975166e-05,
 -2.0851712530551696e-06,
 -4.8091575836902374e-06,
 2.7532569063932553e-05,
 0.11547344108315394,
 -7.265572791621245e-07,
 4.676698474058944e-05,
 -1.1288656052275007e-07,
 1.0000709769921516,
 -2.830210037152877e-06,
 1.7546772168414758e-06,
 -2.040024926419281e-05,
 3.530715055830278e-06,
 7.591416204389917e-07,
 1.1294870014665755e-07,
 -0.004089557984843669,
 -1.746754025009968e-06,
 -1.4967138063467652e-05,
 1.2736272949139042e-06,
 2.4069731393288707e-07,
 4.329722042156208e-05,
 5.33823955975706e-05,
 1.0000023213754912,
 -1.9902100929252282e-08,
 -5.78843317988542e-09,
 6.629846798938191e-06,
 -5.238627768666213e-05,
 2.342703454427629e-05,
 2.6536604608935296e-05,
 -4.2978339287251744e-05,
 -1.4990231372717242e-05,
 7.919097525937174e-08,
 -1.4602131498888887e-05,
 7.03699920710286e-06,
 5.363878362661826e-05,
 1.0596202985528627e-05,
 1.9640044187670476e-08,
 -4.36401529270989e-06,
 4.044330407071319e-06,
 -6.134443813139888e-06,
 6.183567209334786e-08,
 -0.00010233652588147738,
 -2.202667132196045e-06,
 0.2222379789825257,
 -2.040949517685261e-05,
 -2.448816218936132e-05,
 2.2812375514080827e-05,
 1.6083141333671273e-08,
 -2.391161708532428e-05,
 0.9999999935248238,
 -4.338109881205629e-05,
 1.000000930654012,
 -0.00012270708449490985,
 5.498035727488583e-09,
 0.12867647058823525,
 -6.874742506789673e-05,
 -1.2558513181058096e-06,
 6.8739858527779876e-06,
 -1.1669775499040508e-07,
 -3.6674091529307494e-06,
 6.6011661325350614e-09,
 2.9818149031086976e-06,
 4.910158837727473e-05,
 -3.306901609413722e-05,
 0.9998852340624137,
 1.439817393732988e-05,
 7.272267397850528e-06,
 -1.870682542345125e-07,
 2.7679727245930003e-06,
 -4.3754825454927245e-05,
 -0.00011635098966202232,
 -4.786430468503253e-06,
 1.5989349766195372e-05,
 9.046240618954524e-06,
 -1.5700293826866306e-05,
 1.2268942394030752e-05,
 -1.6951258541553463e-08,
 6.405678051999949e-05,
 -1.0691598502723328e-05,
 0.13921348980643947,
 -3.22872762110421e-07,
 3.663648691994227e-06,
 -7.010968585608776e-06,
 0.00029206860704173256,
 5.58162111719403e-05,
 8.597814734008561e-06,
 5.178550665230132e-08,
 1.3267409593910255e-06,
 -7.700027388789415e-05,
 7.779693672578243e-06,
 2.906970580894836e-05,
 -2.70701350044568e-06,
 0.0307935356001237,
 0.11111111123367266,
 3.505624093130398e-05,
 1.3520406916573622e-05,
 5.835693924222781e-08,
 3.740573297764054e-05,
 8.141594478179103e-06,
 0.20586537048694414,
 0.00010997989411141845,
 3.1972965738899704e-06,
 1.3822282589923791e-05,
 -0.00019601217117781966,
 8.165344771428593e-07,
 -1.1011157135846931e-06,
 1.0766445480023418e-05,
 3.84992538755981e-05,
 -1.3723821214782676e-08,
 2.1111616300025324e-05,
 3.343566457705334e-05,
 -1.2661541680684102e-06,
 0.00018259288120835363,
 -2.1633278165426589e-07,
 -2.3254655202642043e-07,
 6.893347274793558e-06,
 1.1562130618307327e-06,
 2.892147772686576e-08,
 1.3896859880133272e-07,
 1.56921934837256e-06,
 -6.845723847147335e-05,
 3.855207828246639e-07,
 4.325524873276615e-06,
 -9.802741483087843e-05,
 3.1529040298971663e-06,
 -2.0393615082059212e-05,
 -1.9521593457696546e-09,
 -2.262173622431727e-06,
 -6.404945725923348e-06,
 0.9999811998085569,
 0.9999986217798073,
 0.11547344108315394,
 -6.133402256324303e-06,
 4.3354241347545744e-08,
 -9.938347720658545e-08,
 1.725222374113549e-08,
 6.190193548658193e-05,
 -1.0187570031719002e-05,
 5.055858145981597e-06,
 3.948624616590523e-06,
 1.7329459945819488e-06,
 0.9999989867860354,
 -7.54769082103264e-05,
 4.219565827338787e-08,
 -1.2895415660176145e-05,
 1.8591142107922423e-05,
 2.321816574414756e-05,
 3.8968792787726584e-05,
 0.9999849592372472,
 -1.799422578689882e-07,
 -6.538340475105912e-05,
 -2.1007649864154788e-08,
 1.0001133284878718,
 4.8135986819777144e-05,
 -3.6207656690086245e-06,
 6.038353288763375e-06,
 1.8938723415716457e-05,
 0.020533229190549195,
 -4.319287767952831e-06,
 3.759513885917425e-05,
 1.3628097135467568e-05,
 -1.168444826416959e-05,
 -4.657687278360699e-05,
 2.2052190528615504e-07,
 -1.9915474812557214e-05,
 -1.27384868324956e-05,
 -3.851716978096003e-05,
 -7.978567188528218e-08,
 1.0000001598671366,
 5.335276667734519e-05,
 3.02272638986874e-05,
 4.7068204926296654e-06,
 0.9999993482447387,
 7.996388883652353e-05,
 -6.337088318874512e-05,
 -1.3846644486142262e-05,
 5.973927095682456e-06,
 -7.157143024236633e-05,
 7.247972489896785e-05,
 -4.152303391854405e-06,
 1.3583520293071008e-07,
 7.598132155932893e-05,
 -0.0001122200850398632,
 -1.4342275801787763e-06,
 6.968323096824032e-05,
 1.0000000027893223,
 9.3481676476261e-06,
 3.1663975519414255e-08,
 -8.831434372852734e-06,
 -9.541526775455837e-07,
 1.0000117440984768,
 -3.4323107384883136e-06,
 -5.355653559148874e-05,
 0.9999996676677207,
 -1.295177652005674e-07,
 1.0000006963597967,
 6.447761795654784e-08,
 1.0920105625309907e-07,
 -1.504095825358112e-08,
 -4.308834023421632e-08,
 0.00018881613407078382,
 8.699229747410988e-05,
 -4.9273044669257e-06,
 -1.2446081781071958e-07,
 4.1484983668320194e-08,
 6.893349206025054e-05,
 4.527955989943766e-06,
 -4.0767392655063415e-07,
 2.246116789215434e-05,
 2.0719098701520064e-06,
 9.163653966465042e-06,
 -3.698194569002016e-08,
 3.915509615908294e-05,
 -8.11705250227369e-06,
 0.00014910753526288414,
 1.0000001125659013,
 2.2850266454537675e-06,
 -1.4844395968888482e-05,
 1.2468590938439007e-05,
 7.1226006851167856e-06,
 3.0248173955440664e-08,
 -1.7882170447444538e-07,
 6.391895981120607e-05,
 -2.128163155680177e-07,
 -6.8814738506428395e-06,
 6.4680638351559804e-06,
 -2.0503525027440154e-05,
 0.20586537048694414,
 8.881727809151812e-06,
 3.910704889282717e-07,
 5.640388452824729e-07,
 -6.387605411615888e-09,
 1.769474301239693e-09,
 0.9999866309158214,
 3.4363452171017334e-05,
 1.1690665916350724e-05,
 1.1903308100683576e-05,
 1.0000096567346426,
 -0.0009290725247064757,
 2.1367263060748835e-09,
 -2.547284425346497e-07,
 -2.278964881181503e-05,
 0.9999028867165589,
 8.430420963800411e-05,
 -0.00015234654967431714,
 -2.3805506678639293e-08,
 -8.907332626035949e-08,
 0.9999044568843792,
 1.487054762938149e-05,
 -3.0832540450436474e-06,
 6.577179435068379e-05,
 2.4292167367440326e-06,
 0.9999876037497804,

In [83]:
columns = ['bad_flag']
sub = pd.DataFrame(data=pred, columns=columns)
sub['UID'] = test_id
sub = sub[['UID','bad_flag']]

In [84]:
sub

            UID      bad_flag
0          Te-1 -8.447665e-06
1          Te-2  1.254994e-05
2          Te-3 -1.264017e-06
3          Te-4 -5.065183e-06
4          Te-5  9.634542e-07
5          Te-6  2.624997e-06
6          Te-7  1.900497e-09
7          Te-8 -3.909852e-06
8          Te-9  1.091810e-05
9         Te-10 -1.283521e-04
10        Te-11  1.450055e-05
11        Te-12  1.581000e-07
12        Te-13  1.154734e-01
13        Te-14  2.585835e-05
14        Te-15 -1.202473e-06
15        Te-16 -2.435993e-05
16        Te-17  8.638308e-06
17        Te-18 -6.573630e-06
18        Te-19 -6.356536e-06
19        Te-20  1.025724e-04
20        Te-21 -1.035187e-06
21        Te-22  3.235666e-06
22        Te-23  2.486407e-05
23        Te-24 -5.699719e-08
24        Te-25  7.337173e-06
25        Te-26 -1.841397e-06
26        Te-27 -1.938128e-05
27        Te-28  3.861074e-05
28        Te-29 -4.493983e-06
29        Te-30  1.647323e-07
...         ...           ...
48404  Te-48405  9.987613e-01
48405  Te-48406 -7.445855e-05
48406  Te-48407 -1.268962e-06
48407  Te-48408  9.999896e-01
48408  Te-48409  8.292803e-09
48409  Te-48410 -4.843853e-06
48410  Te-48411 -1.404299e-06
48411  Te-48412  4.308402e-06
48412  Te-48413  7.999037e-01
48413  Te-48414 -1.608539e-05
48414  Te-48415  5.910487e-03
48415  Te-48416  7.999862e-01
48416  Te-48417  2.032354e-04
48417  Te-48418  1.208049e-06
48418  Te-48419  5.724755e-05
48419  Te-48420  8.001304e-01
48420  Te-48421  9.805353e-07
48421  Te-48422 -1.246538e-04
48422  Te-48423  1.064373e-05
48423  Te-48424  3.970422e-02
48424  Te-48425  3.345115e-08
48425  Te-48426 -2.700634e-06
48426  Te-48427 -6.266880e-07
48427  Te-48428 -1.237302e-04
48428  Te-48429 -3.550635e-04
48429  Te-48430  1.727842e-08
48430  Te-48431  6.942762e-06
48431  Te-48432  2.557668e-06
48432  Te-48433 -2.270909e-08
48433  Te-48434  1.076642e-05

[48434 rows x 2 columns]

In [85]:
sub.to_csv("hdfc.csv", index=False)